package emitter

import (
	"fmt"
	"strings"

	"github.com/DerrickGold/snesrecomp-go/internal/codegen"
	"github.com/DerrickGold/snesrecomp-go/internal/config"
	"github.com/DerrickGold/snesrecomp-go/internal/decoder"
	"github.com/DerrickGold/snesrecomp-go/internal/rom"
)

type BankOptions struct {
	Header            string
	Context           *codegen.Context
	Decode            decoder.Options
	ExcludeRanges     [][2]uint16
	HLESPCUpload      map[uint16]struct{}
	HLEFunctions      map[uint16]string
	HLEDispatch       map[uint16]string
	ExitMX            map[uint32]decoder.MX
	UnresolvedAllowed bool
	CollectFunction   func(config.Entry, *FunctionResult)
}

func EmitBank(image rom.Image, bank byte, entries []config.Entry, options BankOptions) (string, error) {
	header := options.Header
	if header == "" {
		header = defaultBankHeader(bank)
	}
	parts := []string{header, "", "/* Forward declarations for in-bank entries. */"}
	byStart := make(map[uint16]string, len(entries))
	entryPCs := make(map[uint16]struct{}, len(entries))
	for _, entry := range entries {
		base := entry.Name
		if base == "" {
			base = fmt.Sprintf("bank_%02X_%04X", bank, entry.Start)
		}
		parts = append(parts, fmt.Sprintf("RecompReturn %s_M%dX%d(CpuState *cpu);", base, entry.EntryMX.M&1, entry.EntryMX.X&1))
		byStart[entry.Start] = base
		entryPCs[entry.Start] = struct{}{}
	}
	parts = append(parts, "")
	for _, entry := range entries {
		decodeOptions := options.Decode
		decodeOptions.SiblingEntryPCs = make(map[uint16]struct{}, len(entryPCs)-1)
		for pc := range entryPCs {
			if pc != entry.Start {
				decodeOptions.SiblingEntryPCs[pc] = struct{}{}
			}
		}
		var tailName string
		if entry.TailCallPC != nil {
			tailName = byStart[*entry.TailCallPC]
			if tailName == "" {
				return "", fmt.Errorf("bank $%02X: func %q at $%04X declares tail_call:$%04X but no sibling entry exists", bank, entry.Name, entry.Start, *entry.TailCallPC)
			}
		}
		_, hleSPC := options.HLESPCUpload[entry.Start]
		var exitMX *decoder.MX
		entryAddress := decoder.Address24(bank, entry.Start)
		if declared, found := options.ExitMX[entryAddress]; found {
			exitMX = &declared
		}
		result, err := EmitFunction(image, bank, entry.Start, entry.EntryMX.M, entry.EntryMX.X, FunctionOptions{
			Name:              entry.Name,
			End:               entry.End,
			EntrySOffset:      entry.EntrySOffset,
			Decode:            decodeOptions,
			Codegen:           options.Context,
			ExcludeRanges:     options.ExcludeRanges,
			TailCallPC:        entry.TailCallPC,
			TailCallTarget:    tailName,
			HLESPCUpload:      hleSPC,
			HLEFunction:       options.HLEFunctions[entry.Start],
			HLEDispatch:       options.HLEDispatch,
			ExitMX:            exitMX,
			UnresolvedAllowed: options.UnresolvedAllowed,
		})
		if err != nil {
			return "", fmt.Errorf("emit bank $%02X entry $%04X M%dX%d: %w", bank, entry.Start, entry.EntryMX.M&1, entry.EntryMX.X&1, err)
		}
		if options.CollectFunction != nil {
			options.CollectFunction(entry, result)
		}
		parts = append(parts, result.Source, "")
	}
	aliased := make(map[string]struct{})
	for _, entry := range entries {
		if entry.Name == "" {
			continue
		}
		if _, found := aliased[entry.Name]; found {
			continue
		}
		aliased[entry.Name] = struct{}{}
		parts = append(parts, fmt.Sprintf("void %s(CpuState *cpu) {\n  RecompReturn _r = %s_M%dX%d(cpu);\n  if (_r != RECOMP_RETURN_NORMAL) {\n    fprintf(stderr,\n      \"[recomp] non-local-return SKIP_%%d leaked past void alias %%s\\n\",\n      (int)_r, \"%s\");\n    abort();\n  }\n}", entry.Name, entry.Name, entry.EntryMX.M&1, entry.EntryMX.X&1, entry.Name))
	}
	if len(aliased) > 0 {
		parts = append(parts, "")
	}
	return strings.Join(parts, "\n"), nil
}

// ComposeBank assembles independently emitted function bodies in cfg order.
// It is deliberately separate from EmitBank so the regen driver can schedule
// functions—not banks—across workers without changing generated byte order.
func ComposeBank(bank byte, entries []config.Entry, results []*FunctionResult, header string) (string, error) {
	if len(entries) != len(results) {
		return "", fmt.Errorf("bank $%02X: %d entries but %d function results", bank, len(entries), len(results))
	}
	if header == "" {
		header = defaultBankHeader(bank)
	}
	parts := []string{header, "", "/* Forward declarations for in-bank entries. */"}
	for _, entry := range entries {
		base := entry.Name
		if base == "" {
			base = fmt.Sprintf("bank_%02X_%04X", bank, entry.Start)
		}
		parts = append(parts, fmt.Sprintf("RecompReturn %s_M%dX%d(CpuState *cpu);", base, entry.EntryMX.M&1, entry.EntryMX.X&1))
	}
	parts = append(parts, "")
	for index, result := range results {
		if result == nil {
			return "", fmt.Errorf("bank $%02X entry %d has no emit result", bank, index)
		}
		parts = append(parts, result.Source, "")
	}
	aliased := make(map[string]struct{})
	for _, entry := range entries {
		if entry.Name == "" {
			continue
		}
		if _, found := aliased[entry.Name]; found {
			continue
		}
		aliased[entry.Name] = struct{}{}
		parts = append(parts, fmt.Sprintf("void %s(CpuState *cpu) {\n  RecompReturn _r = %s_M%dX%d(cpu);\n  if (_r != RECOMP_RETURN_NORMAL) {\n    fprintf(stderr,\n      \"[recomp] non-local-return SKIP_%%d leaked past void alias %%s\\n\",\n      (int)_r, \"%s\");\n    abort();\n  }\n}", entry.Name, entry.Name, entry.EntryMX.M&1, entry.EntryMX.X&1, entry.Name))
	}
	if len(aliased) > 0 {
		parts = append(parts, "")
	}
	return strings.Join(parts, "\n"), nil
}

func defaultBankHeader(bank byte) string {
	return fmt.Sprintf(`/* Auto-generated by snesrecomp v2 emit_bank. Do NOT hand-edit.
 *
 * Bank $%02X. Each function below mutates the shared CpuState
 * struct via cpu->A / cpu->X / etc. Memory access goes through the
 * cpu_read{8,16} / cpu_write{8,16} helpers in cpu_state.h.
 */

#include <stdio.h>
#include <stdlib.h>

#include "cpu_state.h"
#include "cpu_trace.h"
#include "common_cpu_infra.h"
#include "funcs.h"
`, bank)
}

func DecodeOptionsFromConfig(bank byte, bankConfig *config.Config) decoder.Options {
	options := decoder.Options{
		HLEDispatch:      make(map[uint16]string, len(bankConfig.HLEDispatch)),
		IndirectDispatch: make(map[uint32]decoder.DispatchAuth),
		CalleeExitMX:     make(map[decoder.Variant]decoder.MX),
	}
	for pc, helper := range bankConfig.HLEDispatch {
		options.HLEDispatch[pc] = helper
	}
	for _, region := range bankConfig.DataRegions {
		options.DataRegions = append(options.DataRegions, decoder.DataRegion{Bank: region.Bank, Start: region.Start, End: region.End})
	}
	for _, dispatch := range bankConfig.IndirectDispatch {
		options.IndirectDispatch[decoder.Address24(bank, dispatch.SitePC)] = decoder.DispatchAuth{Count: dispatch.Count, IndexReg: dispatch.IndexReg, TableBases: append([]uint16(nil), dispatch.TableBases...), ReturnPC: dispatch.ReturnPC, SEPMask: dispatch.SEPMask}
	}
	for _, dispatch := range bankConfig.RTSDispatch {
		options.IndirectDispatch[decoder.Address24(bank, dispatch.SitePC)] = decoder.DispatchAuth{RTSTrick: true, Targets: append([]uint16(nil), dispatch.Targets...)}
	}
	for _, exit := range bankConfig.ExitMXAt {
		options.CalleeExitMX[decoder.Variant{Address: exit.Address}] = decoder.MX{M: int8(exit.Exit.M), X: int8(exit.Exit.X)}
	}
	return options
}
