// gencatalog emits C validation facts only; it never reads or embeds ROM data.
package main

import (
	"bytes"
	"encoding/hex"
	"fmt"
	"os"

	"github.com/DerrickGold/ar-recomp/installer/internal/gamerom"
	"github.com/DerrickGold/ar-recomp/installer/internal/regionalmedia"
)

func main() {
	if len(os.Args) != 2 {
		panic("gencatalog needs one output path")
	}
	var b bytes.Buffer
	fmt.Fprintln(&b, "/* Generated by installer/internal/regionalmedia; hashes/schema, no ROM bytes. */")
	fmt.Fprintf(&b, "_Static_assert(kArRegionalMediaVersion == %d && kArRegionalMediaMaximumBytes == %d, \"media header ABI\");\n", regionalmedia.Version, regionalmedia.MaximumBytes)
	fmt.Fprintf(&b, "_Static_assert(kArRegionalMedia_DeathHeimBG2 == %d && kArRegionalMedia_ActionHealthPickup == %d && kArRegionalMedia_ActionSpellHud == %d, \"media resource IDs\");\n", regionalmedia.DeathHeimBG2, regionalmedia.ActionHealthPickup, regionalmedia.ActionSpellHUD)
	fmt.Fprintf(&b, "_Static_assert(kArRegionalMedia_TownFollowerSymbols == %d && kArRegionalMedia_TownLairSymbols == %d && kArRegionalMedia_TownPyramidDetail == %d, \"town media resource IDs\");\n", regionalmedia.TownFollowerSymbols, regionalmedia.TownLairSymbols, regionalmedia.TownPyramidDetail)
	emitHash := func(s string) {
		h, err := hex.DecodeString(s)
		if err != nil || (len(h) != 0 && len(h) != 32) {
			panic("invalid hash")
		}
		fmt.Fprint(&b, "{")
		if len(h) == 0 {
			fmt.Fprint(&b, "0")
		}
		for i, v := range h {
			if i > 0 {
				fmt.Fprint(&b, ",")
			}
			fmt.Fprintf(&b, "0x%02x", v)
		}
		fmt.Fprint(&b, "}")
	}
	fmt.Fprintf(&b, "_Static_assert(kArRegionalMedia_TitleBackground == %d && kArRegionalMedia_Sequence09 == %d && kArRegionalMedia_Sequence12 == %d, \"title/music media resource IDs\");\n", regionalmedia.TitleBackground, regionalmedia.Sequence09, regionalmedia.Sequence12)
	fmt.Fprintf(&b, "_Static_assert(kArRegionalMedia_ActorArt == %d, \"actor drawing media resource ID\");\n", regionalmedia.ActorArt)
	fmt.Fprintln(&b, "static const uint8_t kDonors[][32] = {")
	for _, r := range gamerom.Releases() {
		emitHash(r.SHA256)
		fmt.Fprintln(&b, ",")
	}
	fmt.Fprintln(&b, "};")
	fmt.Fprintln(&b, "static const MediaDefinition kMediaDefinitions[] = {")
	for _, d := range regionalmedia.Definitions() {
		fmt.Fprintf(&b, "{%d,%d,{", d.ID, d.Size)
		for i, r := range gamerom.Releases() {
			if i > 0 {
				fmt.Fprint(&b, ",")
			}
			emitHash(d.Hashes[r.ID])
		}
		fmt.Fprintf(&b, "}}, /* %s */\n", d.Key)
	}
	fmt.Fprintln(&b, "};")
	if err := os.WriteFile(os.Args[1], b.Bytes(), 0644); err != nil {
		panic(err)
	}
}
