package project

import (
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func immutableCacheKey(options HermeticOptions, value string) string {
	if options.InputID == "" {
		return value
	}
	root := filepath.Clean(options.Paths.Root)
	// Arguments here are generated by HermeticBuild, not parsed shell text.
	// Replace only a whole source-root argument or a path below that root.
	parts := strings.Split(value, "\x00")
	for i, part := range parts {
		prefix, suffix := "", ""
		if strings.HasPrefix(part, "-I") {
			prefix, part = "-I", strings.TrimPrefix(part, "-I")
		}
		for _, flag := range []string{"-ffile-prefix-map=", "-fdebug-prefix-map="} {
			if strings.HasPrefix(part, flag) {
				prefix = flag
				part = strings.TrimPrefix(part, flag)
				if index := strings.LastIndexByte(part, '='); index >= 0 {
					part, suffix = part[:index], part[index:]
				}
			}
		}
		if part == root {
			part = "<bundled-inputs>"
		} else if strings.HasPrefix(part, root+string(filepath.Separator)) {
			part = "<bundled-inputs>/" + filepath.ToSlash(strings.TrimPrefix(part, root+string(filepath.Separator)))
		}
		parts[i] = prefix + part + suffix
	}
	return options.InputID + "\x00" + strings.Join(parts, "\x00")
}

func underImmutableRoot(root, path string) bool {
	rel, err := filepath.Rel(root, path)
	return err == nil && (rel == "." || filepath.IsLocal(rel))
}

func validateImmutableOutputs(options HermeticOptions) error {
	digest, err := hex.DecodeString(options.InputID)
	if err != nil || len(digest) != 32 {
		return fmt.Errorf("immutable input identity must be a SHA-256 digest")
	}
	root, err := physicalOutputPath(options.Root)
	if err != nil {
		return err
	}
	for _, path := range []string{options.GeneratedDir, options.FuncsHeader, options.BuildDir} {
		resolved, err := physicalOutputPath(path)
		if err != nil {
			return err
		}
		if path == "" || underImmutableRoot(root, resolved) || underImmutableRoot(resolved, root) {
			return fmt.Errorf("generated sources, headers and build outputs must be outside immutable inputs")
		}
	}
	return nil
}

// Resolve existing ancestors as well as the final component. A writable path
// must not alias the read-only bundle through a pre-existing symlink.
func physicalOutputPath(path string) (string, error) {
	path, err := filepath.Abs(path)
	if err != nil {
		return "", err
	}
	if _, err := os.Lstat(path); err == nil {
		return filepath.EvalSymlinks(path)
	} else if !os.IsNotExist(err) {
		return "", err
	}
	parent := filepath.Dir(path)
	if parent == path {
		return "", fmt.Errorf("cannot resolve output %s", path)
	}
	resolved, err := physicalOutputPath(parent)
	return filepath.Join(resolved, filepath.Base(path)), err
}

func mutableIncludeDirs(options HermeticOptions, dirs []string) []string {
	if options.InputID == "" {
		return dirs
	}
	var result []string
	for _, dir := range dirs {
		if !underImmutableRoot(options.Root, dir) {
			result = append(result, dir)
		}
	}
	return result
}

func immutableObjectFresh(options HermeticOptions, source, object string, newestHeader time.Time) bool {
	if options.InputID == "" || !underImmutableRoot(options.Root, source) {
		return objectFresh(source, object, newestHeader)
	}
	// The verified input digest covers bundled source/headers, independent of
	// extraction timestamps. Mutable generated headers are still tracked.
	info, err := os.Stat(object)
	return err == nil && info.Size() > 0 && info.ModTime().After(newestHeader)
}
