#include "regional/media/regional_media.h"
#include "host/regional_media_files.h"
#include "actraiser/regional/actraiser_regional_media.h"

#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main(int argc,char **argv) {
  ArRegionalMediaView view={.release=kArRegionalMediaRelease_French},before=view;
  unsigned char bad[256]={0};
  for(size_t n=0;n<sizeof(bad);++n) {
    assert(!ArRegionalMedia_Parse(bad,n,&view));assert(!memcmp(&view,&before,sizeof(view)));
  }
  assert(!ArRegionalMedia_Parse(NULL,100,&view));
  assert(!ArRegionalMedia_Parse(bad,sizeof(bad),NULL));
  assert(!ArRegionalMedia_Find(NULL,1).data);
  assert(!ActRaiserRegionalMedia_ActorArt());
  ArRegionalMediaView invalid_actor={.release=kArRegionalMediaRelease_Japan,.count=1,
      .entries={{kArRegionalMedia_ActorArt,{bad,sizeof(bad)}}}};
  assert(!ActRaiserRegionalMedia_AddDonor(&invalid_actor));
  assert(!ActRaiserRegionalMedia_ActorArt());
  ArHostRegionalMediaFiles store={0};char error[128];
  assert(!ArHostRegionalMediaFiles_Load(&store,"",kArRegionalMediaRelease_Japan,error,sizeof(error)) && error[0]);
  assert(!ArHostRegionalMediaFiles_View(&store,kArRegionalMediaRelease_Japan));
  ArHostRegionalMediaFiles_Destroy(&store);ArHostRegionalMediaFiles_Destroy(NULL);
  /* Optional packages are generated by the production Go extractor. No
   * copyrighted fixture data or synthetic bypass enters distributed tests. */
  for(int arg=1;arg<argc;++arg) {
    FILE *file=fopen(argv[arg],"rb");assert(file);
    assert(!fseek(file,0,SEEK_END));long size=ftell(file);
    assert(size>0 && size<=kArRegionalMediaMaximumBytes && !fseek(file,0,SEEK_SET));
    unsigned char *bytes=malloc((size_t)size+1);assert(bytes);
    assert(fread(bytes,1,(size_t)size,file)==(size_t)size);fclose(file);
    assert(ArRegionalMedia_Parse(bytes,(size_t)size,&view));
    assert(ArRegionalMedia_Find(&view,kArRegionalMedia_DeathHeimBG2).size==8192);
    assert(!ArRegionalMedia_Find(&view,0xffffffff).data);
    if(view.release>=kArRegionalMediaRelease_Europe) {
      assert(ArRegionalMedia_Find(&view,kArRegionalMedia_ActionHealthPickup).size==128);
      assert(ArRegionalMedia_Find(&view,kArRegionalMedia_ActionSpellHud).size==768);
    } else assert(!ArRegionalMedia_Find(&view,kArRegionalMedia_ActionHealthPickup).data);
    if(view.release==kArRegionalMediaRelease_Japan) {
      assert(ArRegionalMedia_Find(&view,kArRegionalMedia_TownFollowerSymbols).size==256);
      assert(ArRegionalMedia_Find(&view,kArRegionalMedia_TownLairSymbols).size==128);
      assert(ArRegionalMedia_Find(&view,kArRegionalMedia_TownPyramidDetail).size==32);
      assert(ArRegionalMedia_Find(&view,kArRegionalMedia_TitleBackground).size==33024);
      assert(ArRegionalMedia_Find(&view,kArRegionalMedia_Sequence09).size==2197);
      assert(ArRegionalMedia_Find(&view,kArRegionalMedia_Sequence12).size==1325);
      assert(ArRegionalMedia_Find(&view,kArRegionalMedia_ActorArt).size==480388);
    } else assert(!ArRegionalMedia_Find(&view,kArRegionalMedia_TownFollowerSymbols).data);
    const ArRegionalMediaBytes actor=ArRegionalMedia_Find(&view,kArRegionalMedia_ActorArt);
    const size_t actor_offset=actor.data?(size_t)(actor.data-bytes):(size_t)size;
    for(size_t i=0;i<(size_t)size;++i) {
      ArRegionalMediaView rejected=before;
      /* Keep full structural/truncation coverage, but sample the large,
       * hash-protected actor payload to avoid quadratic hashing work. */
      if(i<actor_offset || i%4096==0 || i==actor_offset || i==(size_t)size-1) {
        bytes[i]^=0x80;
        assert(!ArRegionalMedia_Parse(bytes,(size_t)size,&rejected));
        assert(!memcmp(&rejected,&before,sizeof(before)));bytes[i]^=0x80;
      }
      assert(!ArRegionalMedia_Parse(bytes,i,&rejected));
    }
    bytes[size]=0;assert(!ArRegionalMedia_Parse(bytes,(size_t)size+1,&before));
    const ArRegionalMediaRelease wrong=view.release==1?2:1;
    assert(!ArHostRegionalMediaFiles_Load(&store,argv[arg],wrong,error,sizeof(error)) && !store.implementation);
    assert(ArHostRegionalMediaFiles_Load(&store,argv[arg],view.release,error,sizeof(error)) && !error[0]);
    const ArRegionalMediaView *owned=ArHostRegionalMediaFiles_View(&store,view.release);assert(owned);
    assert(ActRaiserRegionalMedia_AddDonor(owned));
    assert(!ActRaiserRegionalMedia_AddDonor(owned));
    if(view.release==kArRegionalMediaRelease_Japan) {
      const ArRegionalActorArtView *actors=ActRaiserRegionalMedia_ActorArt();
      assert(actors && actors->count==115);
      assert(ArRegionalActorArt_Find(actors,0x0101,kArRegionalActorArt_Characters,0).size==8192);
    } else assert(!ActRaiserRegionalMedia_ActorArt());
    assert(!ArHostRegionalMediaFiles_Load(&store,argv[arg],view.release,error,sizeof(error)));
    free(bytes);assert(ArRegionalMedia_Find(owned,kArRegionalMedia_DeathHeimBG2).size==8192);
    ActRaiserRegionalMedia_ClearDonors();assert(!ActRaiserRegionalMedia_ActorArt());
    ArHostRegionalMediaFiles_Destroy(&store);assert(!store.implementation);
  }
  puts("regional media: bounded parsing, ownership, donor package contracts passed");return 0;
}
