package tooling

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/DerrickGold/snesrecomp-go/internal/config"
)

type namedAddress struct {
	Name    string
	Address uint32
}

// SyncFuncs writes the generated forward-declaration header used by the C
// runner. It is the Go replacement for v2_sync_funcs_h.py.
func SyncFuncs(cfgDir, outputPath string) (int, error) {
	paths, err := filepath.Glob(filepath.Join(cfgDir, "bank*.cfg"))
	if err != nil {
		return 0, fmt.Errorf("find bank cfgs: %w", err)
	}
	sort.Strings(paths)
	seen := make(map[string]struct{})
	var items []namedAddress
	for _, path := range paths {
		cfg, loadErr := config.Load(path)
		if loadErr != nil {
			return 0, loadErr
		}
		for _, entry := range cfg.Entries {
			if entry.Name == "" {
				continue
			}
			if _, found := seen[entry.Name]; found {
				continue
			}
			seen[entry.Name] = struct{}{}
			items = append(items, namedAddress{Name: entry.Name, Address: uint32(cfg.Bank)<<16 | uint32(entry.Start)})
		}
		for _, declaration := range cfg.Names {
			if declaration.Name == "" {
				continue
			}
			if _, found := seen[declaration.Name]; found {
				continue
			}
			seen[declaration.Name] = struct{}{}
			items = append(items, namedAddress{Name: declaration.Name, Address: declaration.Address & 0xffffff})
		}
	}
	sort.SliceStable(items, func(i, j int) bool { return items[i].Address < items[j].Address })

	var source strings.Builder
	source.WriteString("/* Auto-generated by snesrecomp-go sync-funcs.\n")
	source.WriteString(" * Do NOT hand-edit. Every recompiled function takes a\n")
	source.WriteString(" * CpuState* and mutates it in place — no return values, no\n")
	source.WriteString(" * register-packed structs. Drop custom typedefs (HdmaPtrs,\n")
	source.WriteString(" * PairU8, OwHvPos, CollInfo, ExtCollOut, CheckPlatformCollRet,\n")
	source.WriteString(" * CalcTiltPlatformArgs) — all v1 ABI fiction, gone.\n")
	source.WriteString(" *\n")
	source.WriteString(" * Per-(m, x) variants: every named function is declared in\n")
	source.WriteString(" * five forms so cross-bank generated calls can reference any\n")
	source.WriteString(" * variant without a side-car header dependency. Unused\n")
	source.WriteString(" * variants are harmless (C only flags undefined REFERENCES,\n")
	source.WriteString(" * not undefined DECLARATIONS at link time).\n")
	source.WriteString(" */\n#pragma once\n\n#include \"cpu_state.h\"\n\n")
	fmt.Fprintf(&source, "/* %d functions across all banks (5 decls each). */\n\n", len(items))
	for _, item := range items {
		fmt.Fprintf(&source, "void %s(CpuState *cpu);  /* $%02X:%04X alias */\n", item.Name, byte(item.Address>>16), uint16(item.Address))
		for m := 0; m < 2; m++ {
			for x := 0; x < 2; x++ {
				fmt.Fprintf(&source, "RecompReturn %s_M%dX%d(CpuState *cpu);\n", item.Name, m, x)
			}
		}
	}
	source.WriteString("\n/* Hand-written non-recompiled bodies still declared here.\n")
	source.WriteString(" * These are not produced by the v2 emit pipeline but are\n")
	source.WriteString(" * referenced by recompiled code via funcs.h.\n")
	source.WriteString(" */\nvoid ResetSpritesFunc(int wh);\nvoid RunOneFrameOfGame_Internal(void);\n\n")
	source.WriteString("/* Watchdog hook called at every block label. Implemented in\n")
	source.WriteString(" * snesrecomp-go/runtime/src/common_cpu_infra.c.\n")
	source.WriteString(" */\nvoid WatchdogCheck(void);\n")

	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		return 0, fmt.Errorf("create funcs header directory: %w", err)
	}
	if err := os.WriteFile(outputPath, []byte(source.String()), 0o644); err != nil {
		return 0, fmt.Errorf("write funcs header: %w", err)
	}
	return len(items), nil
}
