#include "diorama/diorama_effect_backend.h"

#include <SDL3/SDL.h>
#include <stddef.h>
#include <stdio.h>
#include <string.h>

#include "gpu_shader_blob.h"
#include "platform/sdl/render_sdl_internal.h"
#include "shaders/blur_frag.h"
#include "shaders/dof_edge_frag.h"
#include "shaders/rim_frag.h"

/* Generated by tools/build_shaders.py from the GLSL under src/shaders. The
 * SDL adapter selects MSL, SPIR-V, or DXIL for its current GPU backend; no
 * shader compiler is needed in a hermetic or distributed game build. */
static const GpuShaderBlobs kEffectBlobs[kDioramaEffect_Count] = {
  [kDioramaEffect_Blur] = {
    kBlurFragMSL, kBlurFragMSLSize,
    kBlurFragSPV, kBlurFragSPVSize,
    kBlurFragDXIL, kBlurFragDXILSize,
  },
  [kDioramaEffect_RimLight] = {
    kRimFragMSL, kRimFragMSLSize,
    kRimFragSPV, kRimFragSPVSize,
    kRimFragDXIL, kRimFragDXILSize,
  },
  [kDioramaEffect_DofEdge] = {
    kDofEdgeFragMSL, kDofEdgeFragMSLSize,
    kDofEdgeFragSPV, kDofEdgeFragSPVSize,
    kDofEdgeFragDXIL, kDofEdgeFragDXILSize,
  },
};

static const char *const kEffectNames[kDioramaEffect_Count] = {
  [kDioramaEffect_Blur] = "blur",
  [kDioramaEffect_RimLight] = "rim light",
  [kDioramaEffect_DofEdge] = "DOF",
};

typedef struct DioramaEffectBackendState {
  SDL_Renderer *renderer;
  SDL_GPUDevice *device;
  SDL_GPUShader *shaders[kDioramaEffect_Count];
  SDL_GPURenderState *states[kDioramaEffect_Count];
  bool init_attempted[kDioramaEffect_Count];
  bool available[kDioramaEffect_Count];
} DioramaEffectBackendState;

static DioramaEffectBackendState s_effects;

static bool ValidEffect(DioramaEffectKind effect) {
  return effect >= kDioramaEffect_Blur && effect < kDioramaEffect_Count;
}

static SDL_GPUDevice *RendererGpuDevice(SDL_Renderer *renderer) {
  if (!renderer) return NULL;
  SDL_PropertiesID props = SDL_GetRendererProperties(renderer);
  return props ? (SDL_GPUDevice *)SDL_GetPointerProperty(
      props, SDL_PROP_RENDERER_GPU_DEVICE_POINTER, NULL) : NULL;
}

static bool EnsureEffect(ArRenderDevice *device,
                         DioramaEffectKind effect) {
  if (!ValidEffect(effect) ||
      !ArRenderCapabilities_Has(
          ArRenderDevice_Capabilities(device),
          kArRenderCapability_CustomShaders))
    return false;
  SDL_Renderer *renderer = ArSdlRenderBackend_Renderer(device);
  if (!renderer) return false;
  if (s_effects.renderer && s_effects.renderer != renderer) {
    SDL_SetError("diorama effects belong to another renderer");
    return false;
  }
  if (s_effects.init_attempted[effect])
    return s_effects.available[effect];
  s_effects.init_attempted[effect] = true;
  s_effects.renderer = renderer;

  SDL_GPUDevice *gpu = RendererGpuDevice(renderer);
  if (!gpu) {
    fprintf(stderr,
            "[gpu-fx] renderer has no GPU device - %s disabled "
            "(enable \"GPU shader effects\" in Graphics settings?)\n",
            kEffectNames[effect]);
    return false;
  }
  if (s_effects.device && s_effects.device != gpu) {
    SDL_SetError("diorama effects belong to another GPU device");
    return false;
  }
  s_effects.device = gpu;

  SDL_GPUShader *shader = GpuShaderBlob_CreateFragment(
      gpu, &kEffectBlobs[effect], kEffectNames[effect], 1, 1);
  if (!shader) return false;

  SDL_GPURenderStateCreateInfo state_info;
  SDL_zero(state_info);
  state_info.fragment_shader = shader;
  SDL_GPURenderState *state = SDL_CreateGPURenderState(
      renderer, &state_info);
  if (!state) {
    fprintf(stderr, "[gpu-fx] %s render state creation failed: %s\n",
            kEffectNames[effect], SDL_GetError());
    SDL_ReleaseGPUShader(gpu, shader);
    return false;
  }

  s_effects.shaders[effect] = shader;
  s_effects.states[effect] = state;
  s_effects.available[effect] = true;
  fprintf(stderr, "[gpu-fx] %s shader ready\n", kEffectNames[effect]);
  return true;
}

bool DioramaEffectBackend_IsAvailable(ArRenderDevice *device,
                                      DioramaEffectKind effect) {
  return EnsureEffect(device, effect);
}

static bool BindUniforms(ArRenderDevice *device,
                         DioramaEffectKind effect,
                         const void *uniforms,
                         size_t uniform_size) {
  SDL_Renderer *renderer = ArSdlRenderBackend_Renderer(device);
  if (!renderer || !uniforms || uniform_size == 0 ||
      !EnsureEffect(device, effect))
    return false;
  SDL_GPURenderState *state = s_effects.states[effect];
  return SDL_SetGPURenderStateFragmentUniforms(
             state, 0, uniforms, uniform_size) &&
      SDL_SetGPURenderState(renderer, state);
}

bool DioramaEffectBackend_BindBlur(
    ArRenderDevice *device, const DioramaBlurEffectParams *params) {
  if (!params) return false;
  const struct {
    float texel_width;
    float texel_height;
    float radius;
    float padding;
  } uniforms = {
    params->texel_width, params->texel_height, params->radius, 0.0f,
  };
  return BindUniforms(
      device, kDioramaEffect_Blur, &uniforms, sizeof(uniforms));
}

bool DioramaEffectBackend_BindRimLight(
    ArRenderDevice *device, const DioramaRimLightEffectParams *params) {
  if (!params) return false;
  const struct {
    float texel_width;
    float texel_height;
    float strength;
    float padding;
  } uniforms = {
    params->texel_width, params->texel_height, params->strength, 0.0f,
  };
  return BindUniforms(
      device, kDioramaEffect_RimLight, &uniforms, sizeof(uniforms));
}

bool DioramaEffectBackend_BindDofEdge(
    ArRenderDevice *device, const DioramaDofEdgeEffectParams *params) {
  if (!params) return false;
  /* Keep this field order in lockstep with dof_edge.frag.glsl. */
  const struct {
    float texel_width;
    float texel_height;
    float blur_radius;
    float u_min;
    float u_max;
    float v_min;
    float v_max;
    float edge_feather;
    float lower_content_v_max;
  } uniforms = {
    params->texel_width,
    params->texel_height,
    params->blur_radius,
    params->u_min,
    params->u_max,
    params->v_min,
    params->v_max,
    params->edge_feather,
    params->lower_content_v_max,
  };
  return BindUniforms(
      device, kDioramaEffect_DofEdge, &uniforms, sizeof(uniforms));
}

bool DioramaEffectBackend_Unbind(ArRenderDevice *device) {
  SDL_Renderer *renderer = ArSdlRenderBackend_Renderer(device);
  return renderer && SDL_SetGPURenderState(renderer, NULL);
}

void DioramaEffectBackend_Reset(ArRenderDevice *device) {
  SDL_Renderer *renderer = ArSdlRenderBackend_Renderer(device);
  SDL_GPUDevice *current_device = RendererGpuDevice(renderer);
  const bool same_renderer = !s_effects.renderer ||
      renderer == s_effects.renderer;
  const bool same_device = !s_effects.device ||
      current_device == s_effects.device;

  if (renderer && same_renderer)
    (void)SDL_SetGPURenderState(renderer, NULL);
  if (same_device) {
    for (int effect = 0; effect < kDioramaEffect_Count; effect++)
      SDL_DestroyGPURenderState(s_effects.states[effect]);
  }
  if (same_device && current_device) {
    for (int effect = 0; effect < kDioramaEffect_Count; effect++) {
      if (s_effects.shaders[effect])
        SDL_ReleaseGPUShader(current_device, s_effects.shaders[effect]);
    }
  }
  memset(&s_effects, 0, sizeof(s_effects));
}
