package materialize

import (
	"errors"
	"flag"
	"fmt"
	"io"
	"path/filepath"
	"runtime"
	"strings"
)

// RunCommand is shared by the development CLI and the packaged native driver.
// All relative paths have the same explicit --root semantics on both tools.
func RunCommand(args []string, output io.Writer) error {
	flags := flag.NewFlagSet("materialize", flag.ContinueOnError)
	flags.SetOutput(output)
	root := flags.String("root", ".", "project root for every relative path")
	romPath := flags.String("rom", "game.sfc", "ROM path, relative to --root")
	cfgDir := flags.String("cfg-dir", "recomp", "authored configuration directory, relative to --root (read-only)")
	outDir := flags.String("out-dir", "", "required NEW bundle directory, relative to --root; parent must exist")
	jobs := flags.Int("jobs", runtime.NumCPU(), "parallel analysis and generation workers")
	allowStubs := flags.Bool("allow-stubs", false, "permit existing traps; full/reduced generated bytes must still match")
	if err := flags.Parse(args); err != nil {
		return err
	}
	if flags.NArg() != 0 {
		return errors.New("materialize accepts only named options")
	}
	if strings.TrimSpace(*outDir) == "" {
		return errors.New("materialize requires an explicit new --out-dir")
	}
	if strings.TrimSpace(*romPath) == "" || strings.TrimSpace(*cfgDir) == "" || *jobs < 1 {
		return errors.New("materialize requires nonempty --rom/--cfg-dir and positive --jobs")
	}
	resolvedRoot, err := filepath.Abs(*root)
	if err != nil {
		return err
	}
	resolve := func(path string) string {
		if filepath.IsAbs(path) {
			return path
		}
		return filepath.Join(resolvedRoot, path)
	}
	options := Options{
		ROMPath: resolve(*romPath), ConfigDir: resolve(*cfgDir), OutputDir: resolve(*outDir), Jobs: *jobs, AllowStubs: *allowStubs,
		Progress: func(format string, values ...any) { fmt.Fprintf(output, "materialize: "+format+"\n", values...) },
	}
	report, err := Run(options)
	if err != nil {
		return err
	}
	counts := make(map[string]int)
	for _, removal := range report.Removals {
		counts[removal.Directive]++
	}
	fmt.Fprintf(output, "materialize: removed %d func, %d rts_dispatch, %d indirect_dispatch declarations from the copy; preserved %d HLE directives\n",
		counts["func"], counts["rts_dispatch"], counts["indirect_dispatch"], report.PreservedHLEDirectives)
	fmt.Fprintf(output, "materialize: %d variants, %d unresolved indirect sites, %d stub markers; full/reduced proven-mode output is byte-identical\n",
		report.FinalVariants, report.UnresolvedIndirects, report.StubMarkers)
	fmt.Fprintln(output, "materialize: this is NOT a comparison with default generation or proof of runtime coverage")
	fmt.Fprintf(output, "materialize: keep analysis-db.json with recomp/; gen/ is ready to compile using recomp/funcs.h\nmaterialize: see materialization.json for removed declarations, provenance, and file hashes\n")
	return nil
}
