cmake_minimum_required(VERSION 3.25)
if(NOT BUILDER_DIST_BUILD OR NOT BUILDER_OUTPUT)
    message(FATAL_ERROR "Set BUILDER_DIST_BUILD to a configured Windows installer build and BUILDER_OUTPUT to a new .exe path")
endif()
get_filename_component(BUILDER_DIST_BUILD "${BUILDER_DIST_BUILD}" ABSOLUTE)
get_filename_component(BUILDER_OUTPUT "${BUILDER_OUTPUT}" ABSOLUTE)
if(EXISTS "${BUILDER_OUTPUT}" OR NOT BUILDER_OUTPUT MATCHES "\\.[eE][xX][eE]$")
    message(FATAL_ERROR "Choose a new .exe output path; existing executables are never replaced")
endif()
find_program(_go go REQUIRED)
file(STRINGS "${BUILDER_DIST_BUILD}/CMakeCache.txt" _target_os REGEX "^SNESBUILD_GOOS:STRING=")
file(STRINGS "${BUILDER_DIST_BUILD}/CMakeCache.txt" _target_arch REGEX "^SNESBUILD_GOARCH:STRING=")
if(NOT _target_os STREQUAL "SNESBUILD_GOOS:STRING=windows" OR
   NOT _target_arch MATCHES "^SNESBUILD_GOARCH:STRING=(amd64|arm64)$")
    message(FATAL_ERROR "Builder requires a configured windows/amd64 or windows/arm64 installer payload")
endif()
set(_arch "${CMAKE_MATCH_1}")
set(_lock "${CMAKE_CURRENT_LIST_DIR}/windows-webview2.json")
file(READ "${_lock}" _pins)
string(JSON _schema GET "${_pins}" schema)
if(NOT _schema EQUAL 1)
    message(FATAL_ERROR "Unsupported WebView2 runtime lock schema")
endif()
string(JSON _version GET "${_pins}" runtimes "${_arch}" version)
string(JSON _url GET "${_pins}" runtimes "${_arch}" url)
string(JSON _sha GET "${_pins}" runtimes "${_arch}" sha256)
if(NOT _version MATCHES "^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+$" OR
   NOT _url MATCHES "^https://msedge\\.sf\\.dl\\.delivery\\.mp\\.microsoft\\.com/.*\\.cab$")
    message(FATAL_ERROR "WebView2 lock must name an exact version and official HTTPS CAB")
endif()

# A provided CAB supports offline maintainer builds; it is ALWAYS checked
# against the same pin. Players never download/extract a CAB themselves.
if(BUILDER_WEBVIEW_CAB)
    get_filename_component(_cab "${BUILDER_WEBVIEW_CAB}" ABSOLUTE)
    file(SHA256 "${_cab}" _actual_sha)
    if(NOT _actual_sha STREQUAL _sha)
        message(FATAL_ERROR "Provided WebView2 CAB does not match ${_arch} SHA-256 pin")
    endif()
else()
    if(NOT BUILDER_DOWNLOAD_CACHE)
        set(BUILDER_DOWNLOAD_CACHE "${CMAKE_CURRENT_LIST_DIR}/../packaging/cache/desktop")
    endif()
    file(MAKE_DIRECTORY "${BUILDER_DOWNLOAD_CACHE}")
    set(_cab "${BUILDER_DOWNLOAD_CACHE}/webview2-${_arch}-${_sha}.cab")
    if(EXISTS "${_cab}")
        file(SHA256 "${_cab}" _actual_sha)
        if(NOT _actual_sha STREQUAL _sha)
            message(FATAL_ERROR "Cached WebView2 CAB hash mismatch: ${_cab}")
        endif()
    else()
        file(DOWNLOAD "${_url}" "${_cab}.partial" EXPECTED_HASH "SHA256=${_sha}"
            TLS_VERIFY ON SHOW_PROGRESS STATUS _download)
        list(GET _download 0 _download_status)
        if(NOT _download_status EQUAL 0)
            message(FATAL_ERROR "Could not download pinned WebView2 runtime: ${_download}")
        endif()
        file(RENAME "${_cab}.partial" "${_cab}")
    endif()
endif()
if(CMAKE_HOST_WIN32)
    find_program(_expand expand.exe PATHS "$ENV{SystemRoot}/System32" NO_DEFAULT_PATH REQUIRED)
else()
    find_program(_7zip NAMES 7zz 7z REQUIRED)
endif()
string(RANDOM LENGTH 12 ALPHABET abcdef0123456789 _suffix)
set(_stage "${BUILDER_DIST_BUILD}/builder-shell-${_suffix}")
file(MAKE_DIRECTORY "${_stage}/runtime")
if(CMAKE_HOST_WIN32)
    execute_process(COMMAND "${_expand}" "${_cab}" "-F:*" "${_stage}/runtime"
        OUTPUT_VARIABLE _extract_log COMMAND_ERROR_IS_FATAL ANY)
else()
    execute_process(COMMAND "${_7zip}" x -y "${_cab}" "-o${_stage}/runtime"
        OUTPUT_VARIABLE _extract_log COMMAND_ERROR_IS_FATAL ANY)
endif()
set(_runtime_arch "${_arch}")
if(_arch STREQUAL "amd64")
    set(_runtime_arch x64)
endif()
set(_runtime "${_stage}/runtime/Microsoft.WebView2.FixedVersionRuntime.${_version}.${_runtime_arch}")
if(NOT EXISTS "${_runtime}/msedgewebview2.exe")
    message(FATAL_ERROR "Unexpected CAB layout; review the updated runtime pin before packaging")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${BUILDER_DIST_BUILD}" --parallel 2
    COMMAND_ERROR_IS_FATAL ANY)
execute_process(COMMAND "${CMAKE_COMMAND}" --install "${BUILDER_DIST_BUILD}" --prefix "${_stage}/payload"
    OUTPUT_VARIABLE _install_log COMMAND_ERROR_IS_FATAL ANY)
set(_tags production,wv2runtime.error)
if(BUILDER_SMOKE_TEST)
    string(APPEND _tags ",smoketest")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" -E env "GOOS=windows" "GOARCH=${_arch}" "CGO_ENABLED=0"
    "${_go}" -C "${CMAKE_CURRENT_LIST_DIR}" build -tags "${_tags}" -trimpath
    -ldflags "-s -w -H windowsgui" -o "${_stage}/shell.exe" . COMMAND_ERROR_IS_FATAL ANY)
# The packager runs on the maintainer host, not the Windows target. Do not
# inherit cross-compilation variables into go run.
execute_process(COMMAND "${CMAKE_COMMAND}" -E env --unset=GOOS --unset=GOARCH --unset=CGO_ENABLED
    "${_go}" -C "${CMAKE_CURRENT_LIST_DIR}" run ./cmd/windows-package
    --payload "${_stage}/payload" --shell "${_stage}/shell.exe" --runtime "${_runtime}"
    --runtime-lock "${_lock}" --arch "${_arch}" --output "${BUILDER_OUTPUT}"
    COMMAND_ERROR_IS_FATAL ANY)
message(STATUS "Windows Builder artifact: ${BUILDER_OUTPUT}")
message(STATUS "Unsigned prototype. Perform native Windows acceptance tests before distribution; sign only AFTER packaging.")
