cmake_minimum_required(VERSION 3.25)
if(NOT BUILDER_PLATFORMS)
    message(FATAL_ERROR "Set BUILDER_PLATFORMS to the selected release targets")
endif()
string(REPLACE " " ";" _platforms "${BUILDER_PLATFORMS}")
set(_tools go)
foreach(_platform IN LISTS _platforms)
    if(_platform MATCHES "^macos-")
        if(NOT CMAKE_HOST_SYSTEM_NAME STREQUAL "Darwin")
            message(FATAL_ERROR "macOS desktop artifacts require a macOS host. Use DESKTOP=0 for all CLI archives, or select supported desktop targets.")
        endif()
        list(APPEND _tools clang clang++ codesign ditto xcrun)
    elseif(_platform MATCHES "^linux-" OR _platform STREQUAL "steam-deck")
        if(NOT CMAKE_HOST_SYSTEM_NAME MATCHES "^(Darwin|Linux)$")
            message(FATAL_ERROR "Linux desktop cross-packaging requires macOS or Linux")
        endif()
        list(APPEND _tools pkg-config xz zstd mksquashfs glib-compile-schemas update-mime-database)
        if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Darwin")
            list(APPEND _tools hdiutil)
        endif()
    elseif(_platform MATCHES "^windows-")
        if(CMAKE_HOST_WIN32)
            find_program(_expand expand.exe PATHS "$ENV{SystemRoot}/System32" NO_DEFAULT_PATH REQUIRED)
        else()
            find_program(_7zip NAMES 7zz 7z REQUIRED)
        endif()
    else()
        message(FATAL_ERROR "Unknown desktop target: ${_platform}")
    endif()
endforeach()
list(REMOVE_DUPLICATES _tools)
foreach(_tool IN LISTS _tools)
    find_program(_found_${_tool} NAMES "${_tool}")
    if(NOT _found_${_tool})
        message(FATAL_ERROR "Missing native packaging tool '${_tool}'. See installer/desktop-shell/README.md prerequisites, or use DESKTOP=0.")
    endif()
endforeach()
execute_process(COMMAND "${_found_go}" env GOVERSION OUTPUT_VARIABLE _version
    OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
if(NOT _version MATCHES "^go([0-9]+\\.[0-9]+)")
    message(FATAL_ERROR "Cannot identify installed Go version: ${_version}")
endif()
if(CMAKE_MATCH_1 VERSION_LESS "1.25")
    message(FATAL_ERROR "Desktop packaging requires Go 1.25 or newer; found ${_version}")
endif()
if(_found_xcrun)
    execute_process(COMMAND "${_found_xcrun}" --sdk macosx --show-sdk-path
        OUTPUT_QUIET COMMAND_ERROR_IS_FATAL ANY)
endif()
