# Called after configuring the matching payload; no CLI archive is required.
# Direct packagers never overwrite; this release publisher replaces only its
# explicitly named direct and portable deliverables after one successful build.
cmake_minimum_required(VERSION 3.25)
include("${CMAKE_CURRENT_LIST_DIR}/portable-release.cmake")
set(_platforms macos-arm64 macos-x86_64 linux-x86_64 linux-arm64 windows-x86_64 windows-arm64 steam-deck)
if(NOT BUILDER_PLATFORM IN_LIST _platforms)
    message(FATAL_ERROR "Unknown BUILDER_PLATFORM: ${BUILDER_PLATFORM}")
endif()
if(BUILDER_PLATFORM STREQUAL "steam-deck")
    message(STATUS "Steam Deck: building the glibc-2.36-audited desktop candidate; real-device acceptance is still required")
endif()
get_filename_component(_repo "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
set(_build "${_repo}/installer/packaging/build/${BUILDER_PLATFORM}")
set(_release "${_repo}/release")
if(NOT EXISTS "${_build}/CMakeCache.txt")
    message(FATAL_ERROR "First configure/build installer preset ${BUILDER_PLATFORM}")
endif()
if(BUILDER_PLATFORM MATCHES "^macos-")
    set(_kind macos)
    set(_ext .app)
    set(_published_ext .app.zip)
    find_program(_ditto ditto REQUIRED)
elseif(BUILDER_PLATFORM MATCHES "^linux-" OR BUILDER_PLATFORM STREQUAL "steam-deck")
    set(_kind linux)
    set(_ext .AppImage)
    set(_published_ext .AppImage)
else()
    set(_kind windows)
    set(_ext .exe)
    set(_published_ext .exe)
endif()
set(_filename "ActRaiserRecompBuilder-${BUILDER_PLATFORM}${_published_ext}")
builder_portable_release_name("${BUILDER_PLATFORM}" _portable_filename)
foreach(_path "${_release}"
        "${_release}/${_filename}" "${_release}/${_filename}.sha256"
        "${_release}/${_portable_filename}" "${_release}/${_portable_filename}.sha256")
    if(IS_SYMLINK "${_path}")
        message(FATAL_ERROR "Refusing release symlink: ${_path}")
    endif()
endforeach()
foreach(_leaf "${_filename}" "${_filename}.sha256"
        "${_portable_filename}" "${_portable_filename}.sha256")
    if(IS_DIRECTORY "${_release}/${_leaf}")
        message(FATAL_ERROR "Release output collides with a directory: ${_leaf}")
    endif()
endforeach()
string(RANDOM LENGTH 12 ALPHABET abcdef0123456789 _suffix)
set(_stage "${_build}/desktop-release-${_suffix}")
file(MAKE_DIRECTORY "${_stage}" "${_release}")
set(_app "${_stage}/ActRaiserRecompBuilder${_ext}")
execute_process(COMMAND "${CMAKE_COMMAND}" "-DBUILDER_DIST_BUILD=${_build}"
    "-DBUILDER_OUTPUT=${_app}" "-DBUILDER_LINUX_CROSS=ON"
    -P "${CMAKE_CURRENT_LIST_DIR}/package-${_kind}.cmake" COMMAND_ERROR_IS_FATAL ANY)
set(_artifact "${_app}")
if(_kind STREQUAL "macos")
    set(_artifact "${_stage}/${_filename}")
    execute_process(COMMAND "${_ditto}" -c -k --keepParent --sequesterRsrc "${_app}" "${_artifact}"
        COMMAND_ERROR_IS_FATAL ANY)
endif()
builder_create_portable_release("${_kind}" "${BUILDER_PLATFORM}" "${_app}"
    "${_stage}" _portable_artifact _portable_filename)
file(SHA256 "${_artifact}" _sha)
file(WRITE "${_stage}/${_filename}.sha256" "${_sha}  ${_filename}\n")
file(SHA256 "${_portable_artifact}" _portable_sha)
file(WRITE "${_stage}/${_portable_filename}.sha256"
    "${_portable_sha}  ${_portable_filename}\n")
file(RENAME "${_artifact}" "${_release}/${_filename}")
file(RENAME "${_stage}/${_filename}.sha256" "${_release}/${_filename}.sha256")
file(RENAME "${_portable_artifact}" "${_release}/${_portable_filename}")
file(RENAME "${_stage}/${_portable_filename}.sha256"
    "${_release}/${_portable_filename}.sha256")
file(REMOVE_RECURSE "${_stage}")
message(STATUS "Desktop release: ${_release}/${_filename}")
message(STATUS "Portable release: ${_release}/${_portable_filename}")
