# Called after configuring the matching payload; no CLI archive is required.
# Direct packagers never overwrite; this release publisher replaces
# only its explicitly named generated deliverables, after a successful build.
cmake_minimum_required(VERSION 3.25)
set(_platforms macos-arm64 macos-x86_64 linux-x86_64 linux-arm64 windows-x86_64 windows-arm64 steam-deck)
if(NOT BUILDER_PLATFORM IN_LIST _platforms)
    message(FATAL_ERROR "Unknown BUILDER_PLATFORM: ${BUILDER_PLATFORM}")
endif()
if(BUILDER_PLATFORM STREQUAL "steam-deck")
    message(STATUS "Steam Deck: building the glibc-2.36-audited desktop candidate; real-device acceptance is still required")
endif()
get_filename_component(_repo "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
set(_build "${_repo}/installer/packaging/build/${BUILDER_PLATFORM}")
set(_release "${_repo}/release")
if(NOT EXISTS "${_build}/CMakeCache.txt")
    message(FATAL_ERROR "First configure/build installer preset ${BUILDER_PLATFORM}")
endif()
if(BUILDER_PLATFORM MATCHES "^macos-")
    set(_kind macos)
    set(_ext .app)
    set(_published_ext .app.zip)
    find_program(_ditto ditto REQUIRED)
elseif(BUILDER_PLATFORM MATCHES "^linux-" OR BUILDER_PLATFORM STREQUAL "steam-deck")
    set(_kind linux)
    set(_ext .AppImage)
    set(_published_ext .AppImage)
else()
    set(_kind windows)
    set(_ext .exe)
    set(_published_ext .exe)
endif()
set(_filename "ActRaiserRecompBuilder-${BUILDER_PLATFORM}${_published_ext}")
foreach(_path "${_release}" "${_release}/${_filename}" "${_release}/${_filename}.sha256")
    if(IS_SYMLINK "${_path}")
        message(FATAL_ERROR "Refusing release symlink: ${_path}")
    endif()
endforeach()
if(IS_DIRECTORY "${_release}/${_filename}" OR IS_DIRECTORY "${_release}/${_filename}.sha256")
    message(FATAL_ERROR "Release output collides with a directory")
endif()
string(RANDOM LENGTH 12 ALPHABET abcdef0123456789 _suffix)
set(_stage "${_build}/desktop-release-${_suffix}")
file(MAKE_DIRECTORY "${_stage}" "${_release}")
set(_app "${_stage}/ActRaiserRecompBuilder${_ext}")
execute_process(COMMAND "${CMAKE_COMMAND}" "-DBUILDER_DIST_BUILD=${_build}"
    "-DBUILDER_OUTPUT=${_app}" "-DBUILDER_LINUX_CROSS=ON"
    -P "${CMAKE_CURRENT_LIST_DIR}/package-${_kind}.cmake" COMMAND_ERROR_IS_FATAL ANY)
set(_artifact "${_app}")
if(_kind STREQUAL "macos")
    set(_artifact "${_stage}/${_filename}")
    execute_process(COMMAND "${_ditto}" -c -k --keepParent --sequesterRsrc "${_app}" "${_artifact}"
        COMMAND_ERROR_IS_FATAL ANY)
endif()
file(SHA256 "${_artifact}" _sha)
file(WRITE "${_stage}/checksum" "${_sha}  ${_filename}\n")
file(RENAME "${_artifact}" "${_release}/${_filename}")
file(RENAME "${_stage}/checksum" "${_release}/${_filename}.sha256")
file(REMOVE_RECURSE "${_stage}")
message(STATUS "Desktop release: ${_release}/${_filename}")
