# Manifest for the independently authored portable runner.

set(SNESRECOMP_RUNNER_ROOT ${CMAKE_CURRENT_LIST_DIR})
set(SNESRECOMP_RUNNER_VARIANT next)
set(SNESRECOMP_RUNNER_LEGACY_FALLBACK OFF)
set(SNESRECOMP_RUNNER_DEVICE_ROOT ${SNESRECOMP_RUNNER_ROOT})
set(SNESRECOMP_RUNNER_CRC32_SOURCE ${SNESRECOMP_RUNNER_ROOT}/src/crc32.c)
set(SNESRECOMP_RUNNER_DSP_SOURCE ${SNESRECOMP_RUNNER_ROOT}/src/snes/dsp.c)
set(SNESRECOMP_RUNNER_SAVELOAD_SOURCE ${SNESRECOMP_RUNNER_ROOT}/src/snes/saveload.c)

include(${SNESRECOMP_RUNNER_ROOT}/sources.cmake)

option(SNESRECOMP_ENABLE_TRACE "Build local observability rings and tripwires" OFF)
if(SNESRECOMP_ENABLE_TRACE)
    list(APPEND SNESRECOMP_RUNNER_SOURCES
        ${SNESRECOMP_RUNNER_ROOT}/src/debug_server_stub.c)
endif()

set(SNESRECOMP_RUNNER_INCLUDE_DIRS
    ${SNESRECOMP_RUNNER_ROOT}/src
)
