/* Generated by tools/generate_language_contract_data.py. */
#ifndef AR_LANGUAGE_KEYBOARD_SHAPE_H
#define AR_LANGUAGE_KEYBOARD_SHAPE_H
#define AR_LANGUAGE_KEYBOARD_ROUTE "name_entry.prompt_and_alphabet"
enum {
  kArLanguageKeyboardRows = 5,
  kArLanguageKeyboardColumns = 13,
  kArLanguageKeyboardMaximumLines = 63,
  kArLanguageKeyboardMaximumPageBytes = 3072,
};
#endif
