# Keep only verified AppImage tools in the shared release cache.
include_guard(GLOBAL)

function(appimage_download url destination sha256)
    get_filename_component(_directory "${destination}" DIRECTORY)
    file(MAKE_DIRECTORY "${_directory}")
    foreach(_path "${destination}" "${destination}.part" "${destination}.lock")
        if(IS_SYMLINK "${_path}" OR IS_DIRECTORY "${_path}")
            message(FATAL_ERROR "Refusing unsafe AppImage cache path: ${_path}")
        endif()
    endforeach()
    file(LOCK "${destination}.lock" GUARD FUNCTION TIMEOUT 120 RESULT_VARIABLE _lock)
    if(NOT _lock STREQUAL "0")
        message(FATAL_ERROR "Cannot lock AppImage download cache: ${_lock}")
    endif()
    file(REMOVE "${destination}.part")
    if(EXISTS "${destination}")
        file(SHA256 "${destination}" _cached_sha)
        if(_cached_sha STREQUAL sha256)
            message(STATUS "Using verified AppImage cache: ${destination}")
            return()
        endif()
        file(REMOVE "${destination}")
    endif()
    file(DOWNLOAD "${url}" "${destination}.part" STATUS _status
        TLS_VERIFY ON SHOW_PROGRESS)
    list(GET _status 0 _code)
    list(GET _status 1 _reason)
    if(NOT _code EQUAL 0)
        file(REMOVE "${destination}.part")
        message(FATAL_ERROR "Cannot download pinned AppImage asset ${url}: ${_reason}")
    endif()
    file(SHA256 "${destination}.part" _downloaded_sha)
    if(NOT _downloaded_sha STREQUAL sha256)
        file(REMOVE "${destination}.part")
        message(FATAL_ERROR "AppImage checksum mismatch for ${url}: expected ${sha256}, received ${_downloaded_sha}. Invalid download removed; update the release tag and checksum together if upstream replaced this asset.")
    endif()
    file(RENAME "${destination}.part" "${destination}")
endfunction()
