# One release matrix shared by Make and the CMake orchestrator.
include_guard(GLOBAL)
set(BUILDER_ALL_PLATFORMS macos-arm64 macos-x86_64 linux-x86_64 linux-arm64 windows-x86_64 windows-arm64 steam-deck)

function(builder_release_layout platform legacy out_kind out_name out_retired)
    if(NOT platform IN_LIST BUILDER_ALL_PLATFORMS)
        message(FATAL_ERROR "Unknown release target: ${platform}")
    endif()
    set(_archive "actraiser-recomp-${platform}.tar.xz")
    if(platform MATCHES "^windows-")
        set(_archive "actraiser-recomp-${platform}.zip")
        set(_desktop "ActRaiserRecompBuilder-${platform}.exe")
    elseif(platform MATCHES "^macos-")
        set(_desktop "ActRaiserRecompBuilder-${platform}.app.zip")
    else()
        set(_desktop "ActRaiserRecompBuilder-${platform}.AppImage")
        if(platform STREQUAL "steam-deck")
            set(_archive "actraiser-recomp-steam-deck-x86_64.tar.xz")
        endif()
    endif()
    set(_kind desktop)
    set(_name "${_desktop}")
    set(_retired "${_archive}")
    if(platform MATCHES "^linux-" OR legacy)
        set(_kind archive)
        set(_name "${_archive}")
        set(_retired "${_desktop}")
    endif()
    # Explicit legacy builds must not remove the normal desktop release.
    if(legacy)
        set(_retired "")
    endif()
    set(${out_kind} "${_kind}" PARENT_SCOPE)
    set(${out_name} "${_name}" PARENT_SCOPE)
    set(${out_retired} "${_retired}" PARENT_SCOPE)
endfunction()

# Only remove exact superseded deliverables after their replacement exists.
# Unknown files, player data, symlinks and directories are never removed here.
function(builder_prune_replaced_release platform directory)
    builder_release_layout("${platform}" FALSE _kind _replacement _retired)
    if(IS_SYMLINK "${directory}" OR NOT IS_DIRECTORY "${directory}")
        message(FATAL_ERROR "Release directory must be a real directory: ${directory}")
    endif()
    foreach(_leaf "${_replacement}" "${_replacement}.sha256")
        if(NOT EXISTS "${directory}/${_leaf}" OR IS_DIRECTORY "${directory}/${_leaf}" OR IS_SYMLINK "${directory}/${_leaf}")
            message(FATAL_ERROR "Refusing to prune before replacement publication: ${_leaf}")
        endif()
    endforeach()
    foreach(_leaf "${_retired}" "${_retired}.sha256")
        if(IS_SYMLINK "${directory}/${_leaf}" OR IS_DIRECTORY "${directory}/${_leaf}")
            message(FATAL_ERROR "Refusing unexpected retired release path: ${directory}/${_leaf}")
        endif()
    endforeach()
    foreach(_leaf "${_retired}" "${_retired}.sha256")
        if(EXISTS "${directory}/${_leaf}")
            file(REMOVE "${directory}/${_leaf}")
            message(STATUS "Removed superseded generated release: ${_leaf} (rebuildable with explicit packaging commands)")
        endif()
    endforeach()
endfunction()
