cmake_minimum_required(VERSION 3.25)
include("${CMAKE_CURRENT_LIST_DIR}/release_policy.cmake")
if(NOT DEFINED BUILDER_PLATFORMS)
    set(BUILDER_PLATFORMS "${BUILDER_ALL_PLATFORMS}")
endif()
string(REPLACE " " ";" _selected "${BUILDER_PLATFORMS}")
if(NOT _selected)
    message(FATAL_ERROR "Select at least one release target")
endif()
set(_seen)
set(_desktop_targets)
foreach(_platform IN LISTS _selected)
    builder_release_layout("${_platform}" "${BUILDER_LEGACY_ARCHIVES}" _kind _name _retired)
    if(_platform IN_LIST _seen)
        message(FATAL_ERROR "Duplicate release target: ${_platform}")
    endif()
    list(APPEND _seen "${_platform}")
    if(_kind STREQUAL "desktop")
        list(APPEND _desktop_targets "${_platform}")
        builder_portable_release_name("${_platform}" _portable_name)
        message(STATUS "Release plan: ${_platform} | ${_kind} | ${_name} | portable | ${_portable_name}")
    else()
        message(STATUS "Release plan: ${_platform} | ${_kind} | ${_name}")
    endif()
endforeach()
if(BUILDER_PRINT_PLAN)
    return() # Read-only: no downloads, packaging tools, staging or cleanup.
endif()
if(_desktop_targets)
    set(BUILDER_PLATFORMS "${_desktop_targets}")
    include("${CMAKE_CURRENT_LIST_DIR}/../desktop-shell/preflight.cmake")
endif()
get_filename_component(_repo "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
set(_release "${_repo}/release")
set(_build "${CMAKE_CURRENT_LIST_DIR}/build")
foreach(_path "${_build}" "${_release}")
    if(IS_SYMLINK "${_path}" OR (EXISTS "${_path}" AND NOT IS_DIRECTORY "${_path}"))
        message(FATAL_ERROR "Refusing unexpected build/release directory: ${_path}")
    endif()
endforeach()
set(_configure_options)
foreach(_option SNESBUILD_SDL3_VERSION SNESBUILD_SDL3_TTF_VERSION SNESBUILD_SDL_LOCKFILE)
    if(DEFINED ${_option})
        list(APPEND _configure_options "-D${_option}=${${_option}}")
    endif()
endforeach()
foreach(_platform IN LISTS _selected)
    builder_release_layout("${_platform}" "${BUILDER_LEGACY_ARCHIVES}" _kind _name _retired)
    if(IS_SYMLINK "${_build}/${_platform}")
        message(FATAL_ERROR "Refusing symlinked platform build: ${_platform}")
    endif()
    execute_process(COMMAND "${CMAKE_COMMAND}" --preset "${_platform}" ${_configure_options}
        WORKING_DIRECTORY "${CMAKE_CURRENT_LIST_DIR}" COMMAND_ERROR_IS_FATAL ANY)
    if(_kind STREQUAL "desktop")
        # The desktop publisher builds/stages its payload directly; no CPack
        # archive is compressed just to be thrown away afterwards.
        execute_process(COMMAND "${CMAKE_COMMAND}" "-DBUILDER_PLATFORM=${_platform}"
            -P "${CMAKE_CURRENT_LIST_DIR}/../desktop-shell/release.cmake"
            COMMAND_ERROR_IS_FATAL ANY)
    else()
        get_filename_component(_cmake_bin "${CMAKE_COMMAND}" DIRECTORY)
        find_program(_cpack NAMES cpack HINTS "${_cmake_bin}" REQUIRED)
        execute_process(COMMAND "${CMAKE_COMMAND}" --build --preset "${_platform}"
            WORKING_DIRECTORY "${CMAKE_CURRENT_LIST_DIR}" COMMAND_ERROR_IS_FATAL ANY)
        execute_process(COMMAND "${_cpack}" --preset "${_platform}"
            WORKING_DIRECTORY "${CMAKE_CURRENT_LIST_DIR}" COMMAND_ERROR_IS_FATAL ANY)
    endif()
    if(NOT BUILDER_LEGACY_ARCHIVES)
        builder_prune_replaced_release("${_platform}" "${_release}")
    endif()
    if(NOT BUILDER_KEEP_BUILD)
        file(REMOVE_RECURSE "${_build}/${_platform}")
    endif()
endforeach()
if(IS_SYMLINK "${_release}/_CPack_Packages")
    message(FATAL_ERROR "Refusing symlinked CPack staging directory")
endif()
file(REMOVE_RECURSE "${_release}/_CPack_Packages")
message(STATUS "Releases written to ${_release}; download caches and host toolchain retained")
