# Cross-host staging only: never run target code or install a distro package.
# Package manager metadata and the static library are intentionally excluded.
function(stage_linux_sdl component)
    if(component STREQUAL "SDL3")
        set(_key sdl)
    else()
        set(_key ttf)
    endif()
    string(JSON _pin GET "${_sdl_lock}" ${_key})
    set(_unpack "${CMAKE_BINARY_DIR}/deps/linux-${component}-unpacked")
    # A pin change invalidates all old files for this component. Extract into
    # a fresh private directory so data.tar.* cannot match a previous package.
    file(REMOVE_RECURSE "${_unpack}")
    file(MAKE_DIRECTORY "${_unpack}")
    find_program(_sdl_ar ar REQUIRED)
    foreach(_offset IN ITEMS 0 1)
        string(JSON _url GET "${_pin}" archives ${_offset} url)
        string(JSON _sha GET "${_pin}" archives ${_offset} sha256)
        string(JSON _archive GET "${_pin}" archives ${_offset} archive)
        file(DOWNLOAD "${_url}" "${_cache_dir}/${_archive}"
            EXPECTED_HASH SHA256=${_sha} SHOW_PROGRESS)
        set(_container "${_unpack}/${_offset}")
        file(MAKE_DIRECTORY "${_container}/root")
        execute_process(COMMAND ${_sdl_ar} x "${_cache_dir}/${_archive}"
            WORKING_DIRECTORY "${_container}" COMMAND_ERROR_IS_FATAL ANY)
        file(GLOB _data "${_container}/data.tar.*")
        list(LENGTH _data _count)
        if(NOT _count EQUAL 1)
            message(FATAL_ERROR "Expected one data archive in ${_archive}")
        endif()
        list(GET _data 0 _data)
        execute_process(COMMAND ${CMAKE_COMMAND} -E tar xf "${_data}"
            WORKING_DIRECTORY "${_container}/root" COMMAND_ERROR_IS_FATAL ANY)
    endforeach()
    if(SNESBUILD_GOARCH STREQUAL "amd64")
        set(_multiarch x86_64-linux-gnu)
        set(_machine "3e00")
    elseif(SNESBUILD_GOARCH STREQUAL "arm64")
        set(_multiarch aarch64-linux-gnu)
        set(_machine "b700")
    else()
        message(FATAL_ERROR "Unsupported Linux SDK architecture ${SNESBUILD_GOARCH}")
    endif()
    set(_headers "${_unpack}/0/root/usr/include/${component}")
    file(GLOB _binaries "${_unpack}/1/root/usr/lib/${_multiarch}/lib${component}.so.0.*")
    list(LENGTH _binaries _count)
    if(NOT IS_DIRECTORY "${_headers}" OR NOT _count EQUAL 1)
        message(FATAL_ERROR "Incomplete ${component}/${SNESBUILD_GOARCH} SDK")
    endif()
    list(GET _binaries 0 _binary)
    # Check ELF64/little-endian and e_machine on every host, without running
    # a target executable or relying on a host readelf implementation.
    file(READ "${_binary}" _elf OFFSET 0 LIMIT 20 HEX)
    if(NOT _elf MATCHES "^7f454c460201" OR NOT _elf MATCHES "${_machine}$")
        message(FATAL_ERROR "Wrong ELF architecture for ${component}/${SNESBUILD_GOARCH}")
    endif()
    file(REMOVE_RECURSE "${_sdl_stage}/include/${component}")
    file(MAKE_DIRECTORY "${_sdl_stage}/lib" "${_sdl_stage}/licenses/${component}")
    file(COPY "${_headers}/" DESTINATION "${_sdl_stage}/include/${component}")
    # Real files instead of symlinks remain portable through every host's CPack.
    file(COPY_FILE "${_binary}" "${_sdl_stage}/lib/lib${component}.so.0")
    file(COPY_FILE "${_binary}" "${_sdl_stage}/lib/lib${component}.so")
    if(component STREQUAL "SDL3")
        set(_package libsdl3-0)
    else()
        set(_package libsdl3-ttf0)
    endif()
    file(COPY_FILE "${_unpack}/1/root/usr/share/doc/${_package}/copyright"
        "${_sdl_stage}/licenses/${component}/LICENSE.txt")
    file(WRITE "${_sdl_stage}/${component}.pin" "${_pin}\n")
endfunction()
