#ifndef ACTRAISER_SIM_AI_RUNTIME_H
#define ACTRAISER_SIM_AI_RUNTIME_H
#include "actraiser/actraiser_sim_ai.h"
/* Recompiler hooks for the regional SIM AI rules (hle_func_if in bank01.cfg).
 * Each ...Entry predicate is true when the active regional value differs from
 * the US original; the paired hook then runs the rule in place of the native
 * routine. Written out rather than generated by a macro so that snesbuild
 * doctor and a text search can both find each definition. */
bool ActRaiser_RegionalSimDragonResetEntry(CpuState *cpu);
RecompReturn ActRaiser_RegionalSimDragonReset(CpuState *cpu);
bool ActRaiser_RegionalSimDragonGateEntry(CpuState *cpu);
RecompReturn ActRaiser_RegionalSimDragonGate(CpuState *cpu);
bool ActRaiser_RegionalSimDragonRecursionEntry(CpuState *cpu);
RecompReturn ActRaiser_RegionalSimDragonRecursion(CpuState *cpu);
bool ActRaiser_RegionalSimCandidateEntry(CpuState *cpu);
RecompReturn ActRaiser_RegionalSimCandidate(CpuState *cpu);
bool ActRaiser_RegionalSimPoolEntry(CpuState *cpu);
RecompReturn ActRaiser_RegionalSimPool(CpuState *cpu);
bool ActRaiser_RegionalSimBatChanceEntry(CpuState *cpu);
RecompReturn ActRaiser_RegionalSimBatChance(CpuState *cpu);
bool ActRaiser_RegionalSimBatWaitEntry(CpuState *cpu);
RecompReturn ActRaiser_RegionalSimBatWait(CpuState *cpu);
#endif
