// Generate the ROM-free C catalog from the builder's embedded source.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"strings"

	"github.com/DerrickGold/snesrecomp-go/internal/uicatalog"
)

func cString(text string) string {
	var out strings.Builder
	out.WriteByte('"')
	for _, value := range []byte(text) {
		switch value {
		case '\\', '"', '?':
			out.WriteByte('\\')
			out.WriteByte(value)
		case '\n':
			out.WriteString(`\n`)
		default:
			// Fixed-width octal encodes UTF-8 bytes, not execution-code-page
			// characters. A following digit can never extend this escape.
			if value >= 128 {
				fmt.Fprintf(&out, `\%03o`, value)
			} else {
				out.WriteByte(value)
			}
		}
	}
	out.WriteByte('"')
	return out.String()
}

func main() {
	output := flag.String("output", "", "generated C include")
	check := flag.Bool("check", false, "reject stale output without writing")
	flag.Parse()
	entries, err := uicatalog.Entries()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	var data bytes.Buffer
	fmt.Fprintln(&data, "/* Generated by internal/uicatalog; edit messages.json, then go generate. */")
	fmt.Fprintln(&data, "static const ArUiCatalogEntry kArUiCatalog[] = {")
	for _, entry := range entries {
		if strings.HasPrefix(entry.Key, "builder.") {
			continue
		}
		fmt.Fprintf(&data, "  {%s, {", cString(entry.Key))
		for i, text := range entry.Text {
			if i != 0 {
				fmt.Fprint(&data, ", ")
			}
			fmt.Fprint(&data, cString(text))
		}
		fmt.Fprintln(&data, "}},")
	}
	fmt.Fprintln(&data, "};")
	if *check {
		current, readErr := os.ReadFile(*output)
		if readErr != nil || !bytes.Equal(current, data.Bytes()) {
			err = fmt.Errorf("stale UI catalog: run go generate ./internal/uicatalog")
		}
	} else {
		err = os.WriteFile(*output, data.Bytes(), 0644)
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
