#!/usr/bin/env python3
"""Embed canonical effect text without introducing another source of defaults."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def generate(source, section):
    properties = []
    sections = []
    for raw in source.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith(('#', ';')):
            continue
        if line.startswith('['):
            sections.append(line)
            continue
        if len(sections) == 2 and not line.startswith('enabled='):
            properties.append(line)
    if sections != ['[effects]', section]:
        raise ValueError(f'Expected the canonical field document {section}')
    return ('/* Generated by tools/generate_effect_defaults.py. Edit '
            f'assets/effects/{source.name}. */\n' +
            ''.join(json.dumps(line + '\n') + '\n' for line in properties))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    documents = [
        ('marsh-field', 'action_marsh_field', '[field:02:01:0:marsh-field:B1000000]'),
        ('moon-field', 'action_moon_field', '[field:02:01:0:moon-field:B1000002]'),
        ('forest-ray-field', 'action_ray_field', '[field:01:01:0:ray-field:46000000]'),
        ('cave-water-field', 'action_water_field', '[field:01:02:0:water-field:c2000200]'),
        ('cave-atmosphere-field', 'action_cave_atmosphere', '[field:01:02:0:atmosphere-field:c2000200]'),
        ('temple-atmosphere-field', 'action_temple_atmosphere', '[field:01:03:0:atmosphere-field:c2000300]'),
        ('tower-atmosphere-field', 'action_tower_atmosphere', '[field:01:04:0:atmosphere-field:c2000400]'),
    ]
    documents += [('torch-glow-field','action_torch_glow','[field:02:03:0:glow-field:54000000]'),('temple-glow-field','action_temple_glow','[field:05:04:0:glow-field:54000000]')]
    documents += [(name+'-field','action_'+name,f'[field:{group:02x}:{room:02x}:0:{name}-field:00000000]') for name,group,room in [('trap',2,5),('bolt',2,8),('centaur',1,1)]]
    documents += [(name+'-field','action_'+name.replace('-','_'),f'[field:{group:02x}:{room:02x}:0:{name}-field:00000000]') for name,group,room in [('fireball',2,3),('orb',1,2),('jungle-fire',5,1),('lava-fire',4,4)]]
    documents += [(f'castle-{r}-field', f'action_castle_{r}', f'[field:02:{r:02x}:0:castle-field:ca00000{r}]') for r in range(2,9)]
    documents += [(name+'-field','action_'+name.replace('-','_'),f'[field:04:{room:02x}:0:{name}-field:00000000]') for name,room in [('lava-pit',1),('lava-lake',4),('splash',2),('waterfall',2),('waterfall-mist',2)]]
    for asset, module, section in documents:
        source = ROOT / f'assets/effects/{asset}.ini'
        target = ROOT / f'src/action/{module}_default.inc'
        expected = generate(source, section)
        if args.check:
            if not target.exists() or target.read_text() != expected:
                parser.error('Bundled effects are stale; run tools/generate_effect_defaults.py')
        else:
            target.write_text(expected)



if __name__ == '__main__':
    main()
