#!/usr/bin/env python3
"""Generate the portable C registry for the v1 semantic language catalog."""

import argparse
import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CATALOG = (
    ROOT / 'tools' / 'data' / 'localization' / 'semantic-catalog-v1.json')
DEFAULT_OUTPUT = ROOT / 'src' / 'localization' / 'language_contract_data.inc'
DEFAULT_GO_OUTPUT = (ROOT / 'snesrecomp-go' / 'internal' / 'localizationkit' /
                     'data' / 'author-contracts.json')
PROFILES = ('us', 'eu-en', 'de', 'fr', 'jp')
PRESENTATION_SHAPES = {
    'flow': 'kArLanguagePresentation_Flow',
    'fixed': 'kArLanguagePresentation_Fixed',
    'keyboard': 'kArLanguagePresentation_Keyboard',
    'inline': 'kArLanguagePresentation_Inline',
}
PLACEHOLDER_KINDS = {
    'localized_text': 'kArLanguagePlaceholder_LocalizedText',
    'localized_term': 'kArLanguagePlaceholder_LocalizedTerm',
    'number': 'kArLanguagePlaceholder_Number',
    'icon': 'kArLanguagePlaceholder_Icon',
}


def c_string(value):
    encoded = value.encode('utf-8')
    result = ['"']
    for byte in encoded:
        if byte == 0x22:
            result.append(r'\"')
        elif byte == 0x5c:
            result.append(r'\\')
        elif 0x20 <= byte <= 0x7e:
            result.append(chr(byte))
        else:
            result.append(f'\\x{byte:02x}')
    result.append('"')
    return ''.join(result)


def generate(catalog_path):
    raw = catalog_path.read_bytes()
    catalog = json.loads(raw)
    if catalog.get('format') != 'actraiser-language-semantic-catalog' or \
            catalog.get('version') != 1:
        raise ValueError('unsupported semantic catalog')
    if tuple(catalog.get('release_order', ())) != PROFILES:
        raise ValueError('semantic catalog profile order changed')

    placeholders = sorted(catalog['placeholders'])
    placeholder_index = {name: index for index, name in enumerate(placeholders)}
    routes = catalog['routes']
    if [route['id'] for route in routes] != sorted(
            route['id'] for route in routes):
        raise ValueError('semantic routes must be sorted by id')
    routes = sorted(routes + catalog.get('optional_routes', []), key=lambda r: r['id'])
    if len({route['id'] for route in routes}) != len(routes):
        raise ValueError('duplicate semantic route')

    for route in routes:
        shape = route.get('presentation', {}).get('shape')
        if shape not in PRESENTATION_SHAPES:
            raise ValueError(
                f'{route["id"]}: unknown presentation shape {shape!r}')

    route_placeholder_indices = []
    anchor_names = []
    contracts = []
    generated_routes = []
    for route in routes:
        placeholder_first = len(route_placeholder_indices)
        route_placeholder_indices.extend(
            placeholder_index[name] for name in route['allowed_placeholders'])
        contract_first = len(contracts)
        profile_mask = 0
        for profile_index, profile in enumerate(PROFILES):
            contract = route['contracts'].get(profile)
            if contract is None:
                continue
            profile_mask |= 1 << profile_index
            anchor_first = len(anchor_names)
            anchor_names.extend(
                anchor['id'] for anchor in contract['required_anchors'])
            contracts.append((profile_index, anchor_first,
                              len(contract['required_anchors'])))
        presentation = route['presentation']
        generated_routes.append((
            route['id'], placeholder_first,
            len(route['allowed_placeholders']), contract_first,
            len(contracts) - contract_first, profile_mask,
            PROFILES.index(route['canonical_contract_profile']),
            int(route.get('optional', False)),
            PRESENTATION_SHAPES[presentation['shape']],
            presentation.get('maximum_pages', 0),
            presentation.get('maximum_lines', 0),
            presentation.get('required_nonempty_lines', 0)))

    if max((len(placeholders), len(contracts), len(anchor_names),
            len(route_placeholder_indices))) > 0xffff:
        raise ValueError('generated semantic registry exceeds uint16 indexes')

    lines = [
        '/* Generated by tools/generate_language_contract_data.py.',
        ' * Do not edit by hand. Contains semantic IDs and contracts only;',
        ' * it contains no retail wording, ROM addresses, or extracted bytes.',
        f' * Catalog SHA-256: {hashlib.sha256(raw).hexdigest()}',
        ' */',
        '',
        'static const ArGeneratedPlaceholder kGeneratedPlaceholders[] = {',
    ]
    for name in placeholders:
        kind = PLACEHOLDER_KINDS.get(catalog['placeholders'][name])
        if kind is None:
            raise ValueError(
                f'unknown placeholder kind {catalog["placeholders"][name]!r}')
        lines.append(f'  {{{c_string(name)}, {kind}}},')
    lines.extend(['};', '',
                  'static const uint16_t kGeneratedRoutePlaceholders[] = {'])
    for index in route_placeholder_indices:
        lines.append(f'  UINT16_C({index}),')
    lines.extend(['};', '',
                  'static const char *const kGeneratedAnchorNames[] = {'])
    for name in anchor_names:
        lines.append(f'  {c_string(name)},')
    lines.extend(['};', '',
                  'static const ArGeneratedContract kGeneratedContracts[] = {'])
    for profile, first, count in contracts:
        lines.append(
            f'  {{{profile}, UINT16_C({first}), UINT16_C({count})}},')
    lines.extend(['};', '',
                  'static const ArGeneratedRoute kGeneratedRoutes[] = {'])
    for (route_id, placeholder_first, placeholder_count, contract_first,
         contract_count, profile_mask, canonical_profile, optional, shape,
         maximum_pages, maximum_lines,
         required_nonempty_lines) in generated_routes:
        lines.append(
            f'  {{{c_string(route_id)}, UINT16_C({placeholder_first}), '
            f'UINT16_C({placeholder_count}), UINT16_C({contract_first}), '
            f'UINT16_C({contract_count}), UINT16_C({maximum_lines}), '
            f'UINT8_C({profile_mask}), '
            f'{canonical_profile}, {optional}, {shape}, '
            f'UINT8_C({maximum_pages}), '
            f'UINT8_C({required_nonempty_lines})}},')
    lines.extend(['};', ''])
    return '\n'.join(lines)


def generate_go(catalog_path):
    """Only portable author contracts; no native layouts/addresses or prose."""
    catalog = json.loads(catalog_path.read_bytes())
    # Run the existing schema/order checks before either consumer is emitted.
    generate(catalog_path)
    return json.dumps({
        'placeholders': catalog['placeholders'],
        'routes': [{
            'id': route['id'],
            'allowed_placeholders': route['allowed_placeholders'],
            'canonical_profile': route['canonical_contract_profile'],
            **({'optional': True} if route.get('optional') else {}),
            'presentation': route['presentation'],
            'anchors': {profile: [anchor['id'] for anchor in contract['required_anchors']]
                        for profile, contract in route['contracts'].items()},
        } for route in sorted(catalog['routes'] + catalog.get('optional_routes', []), key=lambda r: r['id'])],
    }, ensure_ascii=False, sort_keys=True, indent=2) + '\n'


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--catalog', type=Path, default=DEFAULT_CATALOG)
    parser.add_argument('--out', type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument('--go-out', type=Path, default=DEFAULT_GO_OUTPUT)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    outputs = {args.out: generate(args.catalog), args.go_out: generate_go(args.catalog)}
    if args.check:
        for path, output in outputs.items():
            if not path.is_file() or path.read_text(encoding='utf-8') != output:
                raise SystemExit(
                    f'{path}: generated language contract data is stale')
        print('language contract data is current')
        return
    for path, output in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(output, encoding='utf-8')
        print(f'wrote {path}')


if __name__ == '__main__':
    main()
