/*
 * Regenerates the compact UAX #29 property table used by the portable game
 * text carrier. This developer-only tool requires utf8proc >= 2.11.3; the
 * shipped game does not link to utf8proc.
 *
 * Example:
 *   cc tools/generate_unicode_grapheme_data.c $(pkg-config --cflags --libs libutf8proc) -o /tmp/generate-graphemes
 *   /tmp/generate-graphemes src/localization/unicode_grapheme_data.inc
 */
#include <errno.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

#include <utf8proc.h>

enum { kMaximumScalar = 0x10FFFFu };

static uint8_t PackedProperties(uint32_t scalar) {
  const utf8proc_property_t *property =
      utf8proc_get_property((utf8proc_int32_t)scalar);
  return (uint8_t)(property->boundclass |
                   (property->indic_conjunct_break << 5u));
}

int main(int argc, char **argv) {
  if (argc != 2) {
    fprintf(stderr, "usage: %s OUTPUT.inc\n", argv[0]);
    return 2;
  }
  FILE *output = fopen(argv[1], "wb");
  if (!output) {
    fprintf(stderr, "%s: %s\n", argv[1], strerror(errno));
    return 1;
  }
  fprintf(output,
      "/* Generated by tools/generate_unicode_grapheme_data.c with "
      "utf8proc %s (Unicode %s).\n"
      " * The values are derived from Unicode data and covered by "
      "third_party/unicode/NOTICE. */\n"
      "static const ArUnicodeGraphemeRange kUnicodeGraphemeRanges[] = {\n",
      utf8proc_version(), utf8proc_unicode_version());

  uint32_t range_start = 0;
  uint8_t previous = PackedProperties(0);
  size_t emitted = 0;
  for (uint32_t scalar = 1; scalar <= kMaximumScalar; ++scalar) {
    const uint8_t current = PackedProperties(scalar);
    if (current == previous) continue;
    if (previous != UTF8PROC_BOUNDCLASS_OTHER) {
      fprintf(output, "  {0x%06Xu, 0x%06Xu, 0x%02Xu},\n",
              range_start, scalar - 1u, previous);
      ++emitted;
    }
    range_start = scalar;
    previous = current;
  }
  if (previous != UTF8PROC_BOUNDCLASS_OTHER) {
    fprintf(output, "  {0x%06Xu, 0x%06Xu, 0x%02Xu},\n",
            range_start, kMaximumScalar, previous);
    ++emitted;
  }
  fprintf(output, "};\n");
  if (fclose(output) != 0) {
    fprintf(stderr, "%s: %s\n", argv[1], strerror(errno));
    return 1;
  }
  fprintf(stderr, "wrote %zu grapheme-property ranges to %s\n",
          emitted, argv[1]);
  return 0;
}
