#!/usr/bin/env python3
"""Generate C tables from the Go-owned address-only USA composer manifest.

The checked manifest and C include contain semantic IDs, native addresses,
destinations, ownership geometry, and indexed-source identities only. They
never contain retail wording, decoded operations, raw bytes, or record hashes.
"""

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

from generate_actraiser_localization_routes import parse_pc24


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MANIFEST = (
    ROOT / 'tools/data/localization/us-runtime-compose-routes-v1.json')
DEFAULT_OUTPUT = (
    ROOT / 'src/actraiser/actraiser_localization_compose_route_data.inc')
FORMAT = 'actraiser-us-runtime-compose-routes'
VERSION = 1


SURFACE_KINDS = json.loads((ROOT /
    'installer/internal/localization/data/us-compose-surfaces.json'
    ).read_text(encoding='utf-8'))


def validate_manifest(manifest):
    if set(manifest) != {
            'format', 'version', 'source_profile', 'rom_sha256',
            'route_count', 'routes'}:
        raise ValueError('compose route manifest has unknown or missing keys')
    if manifest.get('format') != FORMAT or manifest.get('version') != VERSION:
        raise ValueError('unsupported compose route manifest')
    if manifest.get('source_profile') != 'us' or not re.fullmatch(
            r'[0-9a-f]{64}', manifest.get('rom_sha256', '')):
        raise ValueError('compose route manifest has invalid source identity')
    routes = manifest.get('routes')
    if not isinstance(routes, list) or manifest.get('route_count') != len(routes):
        raise ValueError('compose route count is inconsistent')
    identities = set()
    previous_source = -1
    for row in routes:
        required = {'semantic_id', 'source_pc24', 'destination',
                    'surface_kind', 'surface_id', 'region',
                    'native_font_pixels'}
        optional = {'source_table_pc24', 'source_selector'}
        if not required <= set(row) or not set(row) <= required | optional:
            raise ValueError('compose route has unknown or missing keys')
        semantic_id = row['semantic_id']
        if not isinstance(semantic_id, str) or not re.fullmatch(
                r'[A-Za-z][A-Za-z0-9_.-]*', semantic_id):
            raise ValueError('compose route has invalid semantic ID')
        source = parse_pc24(row['source_pc24'])
        if source < previous_source:
            raise ValueError('compose routes are not source-address sorted')
        previous_source = source
        if row['surface_kind'] not in SURFACE_KINDS or \
                row['surface_id'] != SURFACE_KINDS[row['surface_kind']][
                    'surface_id'] or \
                row['destination'] != SURFACE_KINDS[row['surface_kind']][
                    'destination'] or \
                row['region'] != SURFACE_KINDS[row['surface_kind']]['region'] or \
                row['native_font_pixels'] != SURFACE_KINDS[
                    row['surface_kind']]['native_font_pixels']:
            raise ValueError(f'{semantic_id}: invalid surface geometry')
        if not isinstance(row['destination'], int) or not \
                0 <= row['destination'] <= 0xffff:
            raise ValueError(f'{semantic_id}: invalid destination')
        table = row.get('source_table_pc24')
        selector = row.get('source_selector')
        if (table is None) != (selector is None):
            raise ValueError(f'{semantic_id}: incomplete indexed identity')
        if table is not None:
            parse_pc24(table)
            if not isinstance(selector, int) or not 0 <= selector <= 0xffff:
                raise ValueError(f'{semantic_id}: invalid source selector')
        identity = (row['source_pc24'], row['destination'], table, selector)
        if identity in identities:
            raise ValueError(f'{semantic_id}: duplicate compose identity')
        identities.add(identity)
    return routes


def c_u32(value):
    return f'UINT32_C(0x{value:06X})'


def generate_c(manifest_path):
    raw = manifest_path.read_bytes()
    routes = validate_manifest(json.loads(raw))
    lines = [
        '/* Generated by',
        ' * tools/generate_actraiser_localization_compose_routes.py.',
        ' * Do not edit by hand. Contains address-only USA adapter metadata;',
        ' * it contains no retail wording, decoded operations, or raw bytes.',
        f' * Manifest SHA-256: {hashlib.sha256(raw).hexdigest()}',
        ' */',
        '',
        'static const ActRaiserLocalizationComposeRoute kComposeRoutes[] = {',
    ]
    for row in routes:
        flags = []
        kind = row['surface_kind']
        scope = ('Action' if kind.startswith('action_') else
                 'Title' if kind.startswith('title_') else
                 'SoundTest' if kind == 'sound_test' else 'Simulation')
        if 'source_table_pc24' in row:
            flags.append('kActRaiserLocalizationComposeRouteMatch_SourceTable')
            flags.append('kActRaiserLocalizationComposeRouteMatch_Selector')
        lines.extend((
            '  {',
            f'    .source_pc24 = {c_u32(parse_pc24(row["source_pc24"]))},',
            f'    .source_table_pc24 = '
            f'{c_u32(parse_pc24(row["source_table_pc24"]))},'
            if 'source_table_pc24' in row else '',
            f'    .semantic_id = {json.dumps(row["semantic_id"])},',
            f'    .surface_id = UINT32_C({row["surface_id"]}),',
            f'    .scope = kActRaiserLocalizationComposeScope_{scope},',
            f'    .destination = UINT16_C(0x{row["destination"]:04X}),',
            f'    .region = {{{", ".join(str(v) for v in row["region"])}}},',
            f'    .source_selector = UINT16_C({row.get("source_selector", 0)}),',
            f'    .native_font_pixels = UINT8_C('
            f'{row["native_font_pixels"]}),',
            f'    .match_flags = {" | ".join(flags) if flags else "0"},',
            '  },',
        ))
    lines.extend(('};', ''))
    return '\n'.join(line for line in lines if line != '') + '\n'


def write_or_check(path, value, check):
    encoded = value.encode('utf-8')
    if check:
        if not path.exists() or path.read_bytes() != encoded:
            raise ValueError(f'{path}: generated output is stale')
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(encoded)
    print(f'wrote {path}')


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument('--manifest', type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument('--output', type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    try:
        write_or_check(args.output, generate_c(args.manifest), args.check)
        if args.check:
            print('ActRaiser localization compose route data is current')
        return 0
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(f'generate_actraiser_localization_compose_routes: {error}',
              file=sys.stderr)
        return 1


if __name__ == '__main__':
    raise SystemExit(main())
