#!/usr/bin/env python3
"""Generate C tables from the Go-owned address-only USA runtime manifest.

The checked manifest and C include contain semantic IDs, native addresses,
control-flow selectors, and page-unit totals only. They never contain retail
wording, decoded operations, raw bytes, or source-record hashes.
"""

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MANIFEST = (
    ROOT / 'tools/data/localization/us-runtime-dialogue-routes-v1.json')
DEFAULT_OUTPUT = (
    ROOT / 'src/actraiser/actraiser_localization_route_data.inc')
FORMAT = 'actraiser-us-runtime-dialogue-routes'
VERSION = 1
MAX_NATIVE_PAGES = 8
def parse_pc24(value):
    if not isinstance(value, str) or not re.fullmatch(
            r'\$[0-7][0-9A-F]:[89A-F][0-9A-F]{3}', value):
        raise ValueError(f'invalid PC24 address {value!r}')
    return int(value[1:3], 16) << 16 | int(value[4:], 16)


def validate_manifest(manifest):
    if set(manifest) != {
            'format', 'version', 'source_profile', 'rom_sha256',
            'route_count', 'routes'}:
        raise ValueError('runtime route manifest has unknown or missing keys')
    if manifest.get('format') != FORMAT or manifest.get('version') != VERSION:
        raise ValueError('unsupported runtime route manifest')
    if manifest.get('source_profile') != 'us' or not re.fullmatch(
            r'[0-9a-f]{64}', manifest.get('rom_sha256', '')):
        raise ValueError('runtime route manifest has invalid source identity')
    routes = manifest.get('routes')
    if not isinstance(routes, list) or manifest.get('route_count') != len(routes):
        raise ValueError('runtime route count is inconsistent')
    previous_source = -1
    identities = set()
    for row in routes:
        allowed_keys = {
            'semantic_id', 'source_pc24', 'caller_pc24', 'context_pc24',
            'selector_x', 'map_number', 'native_page_units'}
        if not set(row) <= allowed_keys or not {
                'semantic_id', 'source_pc24', 'caller_pc24',
                'native_page_units'} <= set(row):
            raise ValueError('runtime route has unknown or missing keys')
        semantic_id = row.get('semantic_id')
        if not isinstance(semantic_id, str) or not re.fullmatch(
                r'[A-Za-z][A-Za-z0-9_.-]*', semantic_id):
            raise ValueError('runtime route has invalid semantic ID')
        source = parse_pc24(row.get('source_pc24'))
        parse_pc24(row.get('caller_pc24'))
        if source < previous_source:
            raise ValueError('runtime routes are not source-address sorted')
        previous_source = source
        context = row.get('context_pc24')
        if context is not None:
            parse_pc24(context)
        selector = row.get('selector_x')
        if selector is not None and (not isinstance(selector, int) or
                                     not 0 <= selector <= 0xffff):
            raise ValueError(f'{semantic_id}: invalid selector X')
        map_number = row.get('map_number')
        if map_number is not None and (not isinstance(map_number, int) or
                                       not 0 <= map_number <= 0xff):
            raise ValueError(f'{semantic_id}: invalid map number')
        pages = row.get('native_page_units')
        if not isinstance(pages, list) or not 1 <= len(pages) <= \
                MAX_NATIVE_PAGES or any(
                    not isinstance(value, int) or not 1 <= value <= 0xffff
                    for value in pages):
            raise ValueError(f'{semantic_id}: invalid page-unit totals')
        identity = (row['source_pc24'], row['caller_pc24'], context,
                    selector, map_number)
        if identity in identities:
            raise ValueError(f'{semantic_id}: duplicate runtime identity')
        identities.add(identity)
    return routes


def c_u32(value):
    return f'UINT32_C(0x{value:06X})'


def generate_c(manifest_path):
    raw = manifest_path.read_bytes()
    manifest = json.loads(raw)
    routes = validate_manifest(manifest)
    lines = [
        '/* Generated by tools/generate_actraiser_localization_routes.py.',
        ' * Do not edit by hand. Contains address-only USA adapter metadata;',
        ' * it contains no retail wording, decoded operations, or raw bytes.',
        f' * Manifest SHA-256: {hashlib.sha256(raw).hexdigest()}',
        ' */',
        '',
        'static const ActRaiserLocalizationRoute kDialogueRoutes[] = {',
    ]
    for row in routes:
        flags = ['kActRaiserLocalizationRouteMatch_Caller']
        if 'context_pc24' in row:
            flags.append('kActRaiserLocalizationRouteMatch_Context')
        if 'selector_x' in row:
            flags.append('kActRaiserLocalizationRouteMatch_SelectorX')
        if 'map_number' in row:
            flags.append('kActRaiserLocalizationRouteMatch_MapNumber')
        units = ', '.join(str(value) for value in row['native_page_units'])
        lines.extend((
            '  {',
            f'    .source_pc24 = {c_u32(parse_pc24(row["source_pc24"]))},',
            f'    .caller_pc24 = {c_u32(parse_pc24(row["caller_pc24"]))},',
            f'    .context_pc24 = {c_u32(parse_pc24(row["context_pc24"]))},'
            if 'context_pc24' in row else '',
            f'    .selector_x = UINT16_C(0x{row.get("selector_x", 0):04X}),',
            f'    .semantic_id = {json.dumps(row["semantic_id"])},',
            '    .surface_id = kDialogueSurface,',
            '    .region = {5, 19, 23, 7},',
            f'    .native_page_count = {len(row["native_page_units"])},',
            f'    .native_page_units = {{{units}}},',
            '    .native_font_pixels = 7,',
            f'    .match_flags = {" | ".join(flags)},',
            f'    .map_number = UINT8_C({row.get("map_number", 0)}),',
            '  },',
        ))
    lines.extend(('};', ''))
    return '\n'.join(line for line in lines if line != '') + '\n'


def write_or_check(path, value, check):
    encoded = value.encode('utf-8')
    if check:
        if not path.exists() or path.read_bytes() != encoded:
            raise ValueError(f'{path}: generated output is stale')
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(encoded)
    print(f'wrote {path}')


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument('--manifest', type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument('--output', type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    try:
        write_or_check(args.output, generate_c(args.manifest), args.check)
        if args.check:
            print('ActRaiser localization route data is current')
        return 0
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(f'generate_actraiser_localization_routes: {error}', file=sys.stderr)
        return 1


if __name__ == '__main__':
    raise SystemExit(main())
